SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";
-- --------------------------------------------------------

-- Structure de la table `ACTIVITE`

CREATE TABLE `ACTIVITE` (
  `ID_ACTIVITE` int(11) NOT NULL,
  `ID_STRUCTURE` int(11) NOT NULL,
  `LIBELLE_ACT` varchar(50) NOT NULL,
  `ID_VAC_ACT` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Structure de la table `CAMPING`

CREATE TABLE `CAMPING` (
  `ID_CAMPING` int(11) NOT NULL,
  `NOM_CAMPING` varchar(50) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `NUM_SIRET` int(20) NOT NULL,
  `MAP` blob DEFAULT NULL,
  `PASSWORD` varchar(1000) NOT NULL,
  `TOKEN_CONFIRM` int(2) DEFAULT NULL,
  `TOP_USER_CONFIRMED` int(2) NOT NULL,
  `ID_STRUCTURE` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Structure de la table `CAMPING_ACTION`

CREATE TABLE `CAMPING_ACTION` (
  `ID_CAMPING_ACTION` int(11) NOT NULL,
  `DATE_HEURE` int(11) NOT NULL,
  `ID_ACTIVITE` int(11) NOT NULL,
  `ID_CAMPING` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Structure de la table `PLANNING`

CREATE TABLE `PLANNING` (
  `ID_PLANNING` int(11) NOT NULL,
  `ID_ACT_VAC` int(11) NOT NULL,
  `ID_CAMPING_ACTION` int(11) NOT NULL,
  `DATE_HEURE_DEBUT` date NOT NULL,
  `LIB_ACTIVITE` varchar(50) NOT NULL,
  `DATE_HEURE_FIN` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Structure de la table `STRUCTURE`

CREATE TABLE `STRUCTURE` (
  `ID_STRUCTURE` int(11) NOT NULL,
  `ID_CAMPING` int(11) NOT NULL,
  `LIBELLE_STRUCTURE` varchar(50) NOT NULL,
  `NB_STRUCTURE` int(5) NOT NULL,
  `ID_ACTIVITE` int(11) NOT NULL,
  `ETAT_STRUCTURE` enum('Disponible','Indisponible','Réparation','Préparation') DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Structure de la table `VACANCIER`

CREATE TABLE `VACANCIER` (
  `ID_VACANCIER` int(11) NOT NULL,
  `NOM` varchar(20) NOT NULL,
  `PRENOM` varchar(20) NOT NULL,
  `TEL` varchar(20) NOT NULL,
  `SEXE` varchar(10) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `DATE_DEB_VAC` date NOT NULL,
  `DATE_FIN_VAC` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Structure de la table `VAC_ACT`

CREATE TABLE `VAC_ACT` (
  `ID_ACT_VAC` int(11) NOT NULL,
  `ID_ACTIVITE` int(11) NOT NULL,
  `ID_VACANCIER` int(11) NOT NULL,
  `DATE_HEURE` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- Index pour la table `ACTIVITE`

ALTER TABLE `ACTIVITE`
  ADD PRIMARY KEY (`ID_ACTIVITE`),
  ADD KEY `ID_STRUCTURE` (`ID_STRUCTURE`);


-- Index pour la table `CAMPING`

ALTER TABLE `CAMPING`
  ADD PRIMARY KEY (`ID_CAMPING`);


-- Index pour la table `CAMPING_ACTION`

ALTER TABLE `CAMPING_ACTION`
  ADD PRIMARY KEY (`ID_CAMPING_ACTION`),
  ADD KEY `ID_ACTIVITE` (`ID_ACTIVITE`),
  ADD KEY `ID_CAMPING` (`ID_CAMPING`);

-- Index pour la table `PLANNING`

ALTER TABLE `PLANNING`
  ADD PRIMARY KEY (`ID_PLANNING`),
  ADD KEY `ID_ACT_VAC` (`ID_ACT_VAC`),
  ADD KEY `ID_CAMPING_ACTION` (`ID_CAMPING_ACTION`);

-- Index pour la table `STRUCTURE`

ALTER TABLE `STRUCTURE`
  ADD PRIMARY KEY (`ID_STRUCTURE`),
  ADD KEY `ID_CAMPING` (`ID_CAMPING`);

-- Index pour la table `VACANCIER`

ALTER TABLE `VACANCIER`
  ADD PRIMARY KEY (`ID_VACANCIER`);

-- Index pour la table `VAC_ACT`

ALTER TABLE `VAC_ACT`
  ADD PRIMARY KEY (`ID_ACT_VAC`),
  ADD KEY `ID_ACTIVITE` (`ID_ACTIVITE`),
  ADD KEY `ID_VACANCIER` (`ID_VACANCIER`);

-- Contraintes pour la table `ACTIVITE`

ALTER TABLE `ACTIVITE`
  ADD CONSTRAINT `ACTIVITE_ibfk_1` FOREIGN KEY (`ID_STRUCTURE`) REFERENCES `STRUCTURE` (`ID_STRUCTURE`);

-- Contraintes pour la table `CAMPING_ACTION`
-
ALTER TABLE `CAMPING_ACTION`
  ADD CONSTRAINT `CAMPING_ACTION_ibfk_1` FOREIGN KEY (`ID_ACTIVITE`) REFERENCES `ACTIVITE` (`ID_ACTIVITE`),
  ADD CONSTRAINT `CAMPING_ACTION_ibfk_2` FOREIGN KEY (`ID_CAMPING`) REFERENCES `CAMPING` (`ID_CAMPING`);

-- Contraintes pour la table `PLANNING`

ALTER TABLE `PLANNING`
  ADD CONSTRAINT `PLANNING_ibfk_1` FOREIGN KEY (`ID_ACT_VAC`) REFERENCES `VAC_ACT` (`ID_ACT_VAC`),
  ADD CONSTRAINT `PLANNING_ibfk_2` FOREIGN KEY (`ID_CAMPING_ACTION`) REFERENCES `CAMPING_ACTION` (`ID_CAMPING_ACTION`);

-- Contraintes pour la table `STRUCTURE`

ALTER TABLE `STRUCTURE`
  ADD CONSTRAINT `STRUCTURE_ibfk_1` FOREIGN KEY (`ID_CAMPING`) REFERENCES `CAMPING` (`ID_CAMPING`);

-- Contraintes pour la table `VAC_ACT`

ALTER TABLE `VAC_ACT`
  ADD CONSTRAINT `VAC_ACT_ibfk_1` FOREIGN KEY (`ID_ACTIVITE`) REFERENCES `ACTIVITE` (`ID_ACTIVITE`),
  ADD CONSTRAINT `VAC_ACT_ibfk_2` FOREIGN KEY (`ID_VACANCIER`) REFERENCES `VACANCIER` (`ID_VACANCIER`);
COMMIT;

